nowhere.wad: nowhere.lwad nowhere.rwad
	rm -f nowhere.wad
	wadcat -o nowhere.wad nowhere.lwad nowhere.rwad

nowhere.lwad: nowhere.map nowhere.aco
	wadlc nowhere.map tmp.wad
	warm -q tmp.wad
	warm -mraw=nowhere.aco-BEHAVIOR tmp.wad nowhere.lwad
	rm tmp.wad

nowhere.rwad: mapinfo.txt
	mkwad nowhere.rwad @nowhere.res

nowhere.aco: nowhere.acs
	acc nowhere.acs nowhere.aco

clean:
	rm -f *.bak tmp.wad nowhere.lwad nowhere.rwad nowhere.aco
