
.SH AUTHOR
Xwadtools was compiled by Udo Munk <munkudo@aol.com>.
See the individual man pages for detailed author information.

.SH SEE ALSO
.BR yadex (6)
.IP LDE
http://www-unix.oit.umass.edu/~tetron/lde/
.IP PFME
http://www.purplefrog.com/~thoth/purplefrog/editor.html
.IP "Xwad (part of Dumb)"
http://stekt.oulu.fi/~tosi/dumb/dumb.html
.IP Yadex
http://www.teaser.fr/~amajorel/yadex/
