.TH raw2sfx 6 "15 June 2001"

.SH NAME
raw2sfx \- convert raw sound data into id's sfx sound format

.SH SYNOPSIS
.B raw2sfx
.I infile.raw outfile.sfx

.SH DISCLAIMER
This program is furnished on an AS IS basis for the fun of it.
id Software, Raven Software and Activision do not support this program.

.SH DESCRIPTION
This program converts raw sound data (must be unsigned 8bit 11kHz mono data)
into the sfx sound format used by id's WAD based games, so that the output
data file is ready to be included into a WAD file.

.SH SUPPORTED GAMES
Doom, Ultimate Doom, Doom][, Final Doom, Heretic, Hexen, Strife.

.SH SEE ALSO
The Unofficial Doom Specs by Matthew S Fell.
.br
.BR sox "(1), "
.BR xwadtools (6)

.SH BUGS/ERRORS
None.

.SH AUTHOR
.B raw2sfx
was written by Udo Munk (munkudo@aol.com)
